### ISSUE TITLE
imminent collision being detected just for 3 obstacles

### ISSUE THREAD

**Issue by avnishsachar** [WPI-AIR/ramp#4]
number of obstacles for imminent collision is hard coded as 3. Need to find and fix this

**Comment by sapan-ostic** [comment]
Number of obstacles hard-coded in `ramp_planner/src/control_handler.cpp`
Issue closed in https://github.com/WPI-AIR/ramp/commit/0145a60f23b0839e305dc1fe42b5f2b91a342063.
