### ISSUE TITLE
Vector error

### ISSUE THREAD

**Issue by avnishsachar** [WPI-AIR/ramp#9]
Error Instances: 
1. Does not occur for static case
2. Occurs when more than 3 circle_packer_grps (count number of velocity vectors) for dynamical obstacles are identified. 

` vector::_M_range_check: __n (which is 3) >= this->size() ` (which is 3)

**Comment by sapan-ostic** [comment]
![vector_error](https://user-images.githubusercontent.com/19823091/94371656-16bde380-00c6-11eb-80f6-227860a9efd0.png)

**Comment by sapan-ostic** [comment]
Number of obstacles hard-coded in `ramp_planner/src/control_handler.cpp`
Issue closed in https://github.com/WPI-AIR/ramp/commit/0145a60f23b0839e305dc1fe42b5f2b91a342063.
